### PR TITLE
Binary Ninja API updates + improvements to vtable construction

### PR DESCRIPTION
**Pull request by alexrp**

### CODE REVIEW

**Comment by 0x1F9F1** [comment]
Thanks for the fixes. I've added the first two commits, but am very hesitant to completely remove the vftable size limit. Though if you are encountering vftables larger than 64 entries do feel free to create a new PR increasing the limit.

**Comment by alexrp** [comment]
I indeed have an executable (based on Unreal Engine 3) that has some rather huge vtables. If I recall correctly, I had to increase the limit to 512 before I no longer hit it, which prompted me to just remove the limit. I checked the cases with a huge amount of slots (> 256) and all of them seemed legit.

Perhaps the right thing to do would be to query the user for the slot limit when invoking the RTTI scan command?

**Comment by 0x1F9F1** [comment]
> I indeed have an executable (based on Unreal Engine 3) that has some rather huge vtables. If I recall correctly, I had to increase the limit to 512 before I no longer hit it, which prompted me to just remove the limit. I checked the cases with a huge amount of slots (> 256) and all of them seemed legit.
> 
> Perhaps the right thing to do would be to query the user for the slot limit when invoking the RTTI scan command?

Explicitly asking the user wouldn't work well if someone tried to invoke the command by script. Perhaps this would be a good use for the settings API.

**Comment by alexrp** [comment]
Wouldn't [this API](https://api.binary.ninja/binaryninja.interaction-module.html#binaryninja.interaction.get_int_input) work if we called it in `__init__.py`? It queries the user on the command line too.

**Comment by 0x1F9F1** [comment]
> Wouldn't [this API](https://api.binary.ninja/binaryninja.interaction-module.html#binaryninja.interaction.get_int_input) work if we called it in `__init__.py`? It queries the user on the command line too.

I mean if the user does something like this, where they aren't expecting to provide any input
```py
ctx = PluginCommandContext(bv)
PluginCommand.get_valid_list(ctx)[r'Windows\Scan for RTTI'].execute(ctx)
```

**Pull request closed without merging**
